
POST /api/user/game HTTP/1.1
Host: localhost:8081
Content-Type: application/json
Authorization: Bearer

{
  "owner": "67bcbc86-a3c6-4d37-a13c-7eb8eeee7258",
  "enemy": "moha",
  "win": true,
  "xp": 20
}