
GET /api/user/me HTTP/1.1
Host: localhost:8081
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIyZDdmMzU4My05MDdkLTQ4ZDQtODRiMi1mYzU1ODcwOTYyYzAiLCJpc3MiOiJNeUFwcCIsImV4cCI6MTcwNDk4MDcyMCwiaWF0IjoxNzA0OTc4OTIwfQ.lQ4ngynm9GfQ6Q7brBvzgCChh7pbPSKEqhd1zCJOjiFd-MdwRIJZfu6iIWEgjIH_ExYXL7HkVXfpVIYOasKX0Q