
GET /api/user/users HTTP/1.1
Host: localhost:8081
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI2NDhkYzdiZC0zMzA5LTRlZmItOWQ3Mi1hYzQ1ZGZhZDRiYWMiLCJpc3MiOiJNeUFwcCIsImV4cCI6MTcwODM2MDE3OCwiaWF0IjoxNzA4MzU4Mzc4fQ.3eGwGcgAVnSPaVm39vyxupqeQEjWkCNGsih0Ied6CK6TFc9HHhzyupj-l2HcC0PdeqatTtfb6NexU5HzQf4gRA